### ISSUE TITLE
syntax error, unexpected 'int' (T_STRING)

### ISSUE THREAD

**Issue by TbagZz** [Allyans3/steam-market-api-v2#1]
Hi, I installed this package on laravel 8 and now i get the following error : 

ParseError
syntax error, unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
(vendor\allyans3\steam-market-api-v2\src\Requests\MarketListings.php:12)

what is the problem here ?

**Comment by Allyans3** [comment]
Hello. What version of PHP are you using? Can you represent this error? What parameters do you use in the method?

**Comment by Allyans3** [comment]
I removed the types. Please update the package and give feedback.

**Comment by TbagZz** [comment]
problem solved and i'm using php 7 btw and now UserinventoryV2 not working well : 
ErrorException
Undefined index: assetid

**Comment by Allyans3** [comment]
Ok i fixed UserinventoryV2 bug. I need to optimize this method and i will push changes.

**Comment by Allyans3** [comment]
Pushed new changes. Give feedback please)

**Comment by TbagZz** [comment]
it's ok rn but can you add cache_expiration in Userinventoryv2? it's for tradeban ending date

**Comment by Allyans3** [comment]
Ok

**Comment by Allyans3** [comment]
Released. I found some strange (rare) bug in UserInventory.php (. Hope will be fixed in short time.

**Comment by Allyans3** [comment]
Fixed
