### ISSUE TITLE
Rust game doesn't work

### ISSUE THREAD

**Issue by MrFallen** [Allyans3/steam-market-api-v2#12]
`$api->detailed()->getItemListings(252490, $options);`

Doesn't work with Rust game.

Undefined array key "actions"

`'inspect_link' => str_replace("%assetid%", $asset['id'], $asset['actions'][0]['link'])`

**Comment by Allyans3** [comment]
This package only work with 730 (CS:GO) game.

**Comment by Allyans3** [comment]
Fixed in latest 4.2.2 version
