### ISSUE TITLE
SearchItems method microbans

### ISSUE THREAD

**Issue by donvardix** [Allyans3/steam-market-api-v2#14]
I made my own tests for this method and decided to share the results.
After 5 minutes the ban was removed.

Result: 25 / 5 min

![res](https://github.com/Allyans3/steam-market-api-v2/assets/15367221/926410ae-87dd-4276-b709-303cb4cf8265)

**Comment by Allyans3** [comment]
Thank you for helping improve the documentation. I added the result to the table.
