### ISSUE TITLE
Incoming Offers request not working

### ISSUE THREAD

**Issue by kovalovme** [Allyans3/steam-market-api-v2#17]
Good day sir!

[Incoming Offers](https://github.com/Allyans3/steam-market-api-v2/wiki/Trade-Offer-Methods#incoming-offers) request results in curl max redirects (default 20) reached.  
I've investigated this issue and I assume that this issue is connected with additional steam security redirects with additional cookie append, tried to set  `CURLOPT_COOKIEFILE => ''` in `SteamApi\Engine\Request` and it let me into the page but offer list is empty.

Any ideas why this might happen and how to fix it? Cookies are fresh and working with other requests, I'm having issues only with this request.

Thanks!

**Comment by kovalovme** [comment]
@Allyans3 
Trade Offer Creation also not working

**Comment by umpak** [comment]
Did you make it work? @kovalovme 
this is my code

```
$api = new SteamApi();

 $tradeLink = 'https://steamcommunity.com/tradeoffer/new/?partner=159******&token=*******';

$formData = [
    'partner_id' => '765611981********',         //optional
    'message' => 'message',                    //optional
    'my_items' => [],
    'partner_items' => [
        [
            "app_id" => 730,
            "context_id" =>  "2",
            "amount" =>  1,
            "asset_id" => '33781946914'
        ],
    ]
];

dd($api->detailed()
       ->withCustomCurlOpts([CURLOPT_COOKIEFILE => 'cookie.txt'])
       ->createTradeOffer($tradeLink, $formData));

       var_dump(dd());
```

here is the response, help me work it out please, it's said I'm Unauthorized. @Allyans3 

```
array(11) {
["request_headers"]=> array(7) {
["Host"]=> string(18) "steamcommunity.com"
["Accept"]=> string(3) "*/*"
["Cookie"]=> string(209) "steamMachineAuth76561199*********=DA054C4D************************************; steamLoginSecure=76561199*********%7C%7C5CEC16A*************************************; steamCountry=SG%7C3e6faea5d51124******************;"
["Origin"]=> string(27) "https://steamcommunity.com/"
["Referer"]=> string(75) "https://steamcommunity.com/tradeoffer/new/?partner=159******&token=********"
["Content-Length"]=> string(3) "505"
["Content-Type"]=> string(33) "application/x-www-form-urlencoded" }
["response_headers"]=> array(11) {
["Server"]=> string(5) "nginx"
["Content-Type"]=> string(31) "application/json; charset=utf-8"
["Vary"]=> string(15) "Accept-Encoding"
["X-Frame-Options"]=> string(10) "SAMEORIGIN"
["Expires"]=> string(29) "Mon, 26 Jul 1997 05:00:00 GMT"
["Cache-Control"]=> string(8) "no-cache"
["Content-Encoding"]=> string(4) "gzip"
["Content-Length"]=> string(2) "24"
["Date"]=> string(29) "Tue, 17 Oct 2023 19:17:43 GMT"
["Connection"]=> string(5) "close"
["Set-Cookie"]=> string(99) "browserid=285477753**********; Expires=Wed, 16 Oct 2024 19:17:43 GMT; Path=/; Secure; SameSite=None" }
["url"]=> string(46) "https://steamcommunity.com/tradeoffer/new/send"
["code"]=> int(401)
["message"]=> string(12) "Unauthorized"
["error"]=> string(0) ""
["cookies"]=> array(2) {
["sessionid"]=> string(24) "c330ec27d49602**********"
["browserid"]=> string(19) "285477753**********" }
["remote_ip"]=> string(12) "104.69.**.**"
["local_ip"]=> string(15) "191.101.***.***"
["total_time"]=> string(3) "860"
["response"]=> bool(false) }
```

**Comment by Allyans3** [comment]
I researched both cases and came to this conclusion:

1. Regarding Incoming Offers, Steam sends the updated offer status only once (let's say you received a list of active offers, then it was confirmed/cancelled or the sender canceled it, after that you will request a list of offers and you will see one of the updated statuses, when you request offers again you will receive an empty list). The history of offers has been broken for half a year, both incoming and outgoing. This can be checked directly in the web version of Steam.
2. Regarding Trade Offer Creation, everything works fine for me, I received fresh cookies, used the cookie file in the request, and used the $formData as in the example, using my data. As a result, the offer was created. Take a closer look at the cookies and data you are sending.
