### ISSUE TITLE
Creating trade offer, Unauthorized

### ISSUE THREAD

**Issue by umpak** [Allyans3/steam-market-api-v2#18]
Can someone help me work, on creating a trade offer, I got Unauthorized. What did I miss

```
$api = new SteamApi();

 $tradeLink = 'https://steamcommunity.com/tradeoffer/new/?partner=159******&token=*******';

$formData = [
    'partner_id' => '765611981********',         //optional
    'message' => 'message',                    //optional
    'my_items' => [],
    'partner_items' => [
        [
            "app_id" => 730,
            "context_id" =>  "2",
            "amount" =>  1,
            "asset_id" => '33781946914'
        ],
    ]
];

dd($api->detailed()
       ->withCustomCurlOpts([CURLOPT_COOKIEFILE => 'cookie.txt'])
       ->createTradeOffer($tradeLink, $formData));

       var_dump(dd());
```

here is the response, help me work it out please, it's said I'm Unauthorized. @Allyans3 

```
array(11) {
["request_headers"]=> array(7) {
["Host"]=> string(18) "steamcommunity.com"
["Accept"]=> string(3) "*/*"
["Cookie"]=> string(209) "steamMachineAuth76561199*********=DA054C4D************************************; steamLoginSecure=76561199*********%7C%7C5CEC16A*************************************; steamCountry=SG%7C3e6faea5d51124******************;"
["Origin"]=> string(27) "https://steamcommunity.com/"
["Referer"]=> string(75) "https://steamcommunity.com/tradeoffer/new/?partner=159******&token=********"
["Content-Length"]=> string(3) "505"
["Content-Type"]=> string(33) "application/x-www-form-urlencoded" }
["response_headers"]=> array(11) {
["Server"]=> string(5) "nginx"
["Content-Type"]=> string(31) "application/json; charset=utf-8"
["Vary"]=> string(15) "Accept-Encoding"
["X-Frame-Options"]=> string(10) "SAMEORIGIN"
["Expires"]=> string(29) "Mon, 26 Jul 1997 05:00:00 GMT"
["Cache-Control"]=> string(8) "no-cache"
["Content-Encoding"]=> string(4) "gzip"
["Content-Length"]=> string(2) "24"
["Date"]=> string(29) "Tue, 17 Oct 2023 19:17:43 GMT"
["Connection"]=> string(5) "close"
["Set-Cookie"]=> string(99) "browserid=285477753**********; Expires=Wed, 16 Oct 2024 19:17:43 GMT; Path=/; Secure; SameSite=None" }
["url"]=> string(46) "https://steamcommunity.com/tradeoffer/new/send"
["code"]=> int(401)
["message"]=> string(12) "Unauthorized"
["error"]=> string(0) ""
["cookies"]=> array(2) {
["sessionid"]=> string(24) "c330ec27d49602**********"
["browserid"]=> string(19) "285477753**********" }
["remote_ip"]=> string(12) "104.69.**.**"
["local_ip"]=> string(15) "191.101.***.***"
["total_time"]=> string(3) "860"
["response"]=> bool(false) }
```

**Comment by Allyans3** [comment]
Answered in https://github.com/Allyans3/steam-market-api-v2/issues/17#issuecomment-1767959311

**Comment by umpak** [comment]
I use 2 days cookie.txt but when I try to login first and use a fresh cookie, it is the same response.
Unauthorized, maybe because of assetid? because I use 3rd party APIs like Steamapis to get user inventory and maybe give me different assetid?  
@Allyans3

**Comment by umpak** [comment]
i replace the dd() to 

```
$result = $api->detailed()
    ->withCustomCurlOpts([CURLOPT_COOKIEFILE => 'cookie.txt'])
    ->createTradeOffer($tradeLink, $formData);


       var_dump($result);
       
       echo $response->someProperty;
```
giving me Unauthorized response.

**Comment by umpak** [comment]
Update😩😩😩, [code] => 500, [message] => Internal Server Error @Allyans3 
``` 
Array
(
    [request_headers] => Array
        (
            [Host] => steamcommunity.com
            [Accept] => */*
            [Cookie] => steamMachineAuth********=********;  steamLoginSecure=********; steamCountry=********; sessionid=********;
            [Origin] => https://steamcommunity.com/
            [Referer] => https://steamcommunity.com/tradeoffer/new/?partner=********&token=********
            [Content-Length] => 529
            [Content-Type] => application/x-www-form-urlencoded
        )

    [response_headers] => Array
        (
            [Server] => nginx
            [Content-Type] => application/json; charset=utf-8
            [Vary] => Accept-Encoding
            [X-Frame-Options] => SAMEORIGIN
            [Expires] => Mon, 26 Jul 1997 05:00:00 GMT
            [Cache-Control] => no-cache
            [Content-Encoding] => gzip
            [Content-Length] => 101
            [Date] => Mon, 23 Oct 2023 06:33:45 GMT
            [Connection] => close
        )

    [url] => https://steamcommunity.com/tradeoffer/new/send
    [code] => 500
    [message] => Internal Server Error
    [error] => 
    [cookies] => Array
        (
        )

    [remote_ip] => 104.69.***.***
    [local_ip] => 191.101.***.***
    [total_time] => 479
    [response] => 
)
```

**Comment by Allyans3** [comment]
The HTTP code 500 is a server-side error that does not belong to my library.

**Comment by umpak** [comment]
Yes, its works already, my cookie is the problem, I edit my cookie.txt like my browser cookies.
Its returning tradeofferid now. thank you so much @Allyans3 

my problem now is to accept in my SDA, 
when my code reach this, my code stop and return empty
```
$api->detailed()
       ->withCustomCurlOpts([CURLOPT_COOKIEFILE => 'cookie.txt'])
       ->getMobileConfList($options)
```
I can't confirm the trade offer, please help @Allyans3

**Comment by Allyans3** [comment]
You shouldn't create/edit cookie.txt. It must be generated using the library https://github.com/Allyans3/protobuf-steam-auth.

All your errors are related either to cookies or to the options that you send. You should update your cookies every day because Steam access_token lifetime is one day.

**Comment by umpak** [comment]
@Allyans3  helpppppppppp, I cant install the command 

```
phpize
./configure
make
make install
```

its not working for me

**Comment by umpak** [comment]
PS \steamauth\protobuf-ext> cd php8
PS \steamauth\protobuf-ext\php8> $ phpize
$ : The term '$' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ $ phpize
+ ~
    + CategoryInfo          : ObjectNotFound: ($:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS \steamauth\protobuf-ext\php8> $phpize
PS \steamauth\protobuf-ext\php8> $./configure
$./configure : The term '$./configure' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ $./configure
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ($./configure:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS \steamauth\protobuf-ext\php8> $/configure
$/configure : The term '$/configure' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ $/configure
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ($/configure:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS \steamauth\protobuf-ext\php8> $configure
PS \steamauth\protobuf-ext\php8> $make
PS \steamauth\protobuf-ext\php8> $make install
At line:1 char:7
+ $make install
+       ~~~~~~~
Unexpected token 'install' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS \steamauth\protobuf-ext\php8> cd $make
cd : Cannot process argument because the value of argument "path" is null. Change the value of argument "path" to a
non-null value.
At line:1 char:1
+ cd $make
+ ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentNullException
    + FullyQualifiedErrorId : ArgumentNull,Microsoft.PowerShell.Commands.SetLocationCommand``

**Comment by umpak** [comment]
PS \steamauth> cd protobuf-ext/php8
>>
>> phpize
>> ./configure
>> make
>> make install
phpize : The term 'phpize' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:3 char:1
+ phpize
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (phpize:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

./configure : The term './configure' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:4 char:1
+ ./configure
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./configure:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:5 char:1
+ make
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:6 char:1
+ make install
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException``

**Comment by umpak** [comment]
Do I make a file protobuf.so?
and put a code inside it

```
cd protobuf-ext/php8

phpize
./configure
make
make install
```

**Comment by umpak** [comment]
Do I make a file protobuf.so?
and put a code inside it

```
cd protobuf-ext/php8

phpize
./configure
make
make install
```

@Allyans3 help me pleaseeee 😩
