### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by frisatore** [Allyans3/steam-market-api-v2#2]
i dont even know how to run this thing what does it need can you reply me your discord or something ? :D

**Comment by Allyans3** [comment]
Hi!) My Discord: Allyans3#5066

**Comment by Allyans3** [comment]
1. Install with composer: composer require allyans3/steam-market-api-v2
2. Create object: $api = new SteamApi();
3. Use any method you need.

**Comment by frisatore** [comment]
add me on discord please
