### ISSUE TITLE
Undefined array key "currency"

### ISSUE THREAD

**Issue by amsonline** [Allyans3/steam-market-api-v2#4]
Hi. When I execute the code, I get this error:

```
 ErrorException 

  Undefined array key "currency"

  at vendor/allyans3/steam-market-api-v2/src/Responses/MarketListings.php:63
```

It happens when the response from Steam does not contain a currency field

**Comment by Allyans3** [comment]
Pushed fix but I want to see your request parameters.

**Comment by amsonline** [comment]
@Allyans3 Thanks for quick response. This was my $options:
```
				$options = [
					'start'       => 0,
					'count'       => 100,
					'sort_column' => 'name',
					'sort_dir'    => 'asc',
				];
```
And used appId 730 (Counter-Strike Global Offensive). It always threw error for the first item.
Note that I am living in Turkey and my currency is now TRY. Before that, I lived in Iran and my Steam currency was USD. This may help

**Comment by Allyans3** [comment]
Unfortunately, i can't check this without proxy. Can you convert response to json file and send me or copy piece of item from response where the currency field could have been. Is the latest fix working fine?
