### ISSUE TITLE
error Request.php

### ISSUE THREAD

**Issue by Giza** [Allyans3/steam-market-api-v2#6]
36                CURLOPT_URL => self::mergeHeaders($this->getUrl())
what?))

microbans are still there.

**Comment by Allyans3** [comment]
fixed :)

**Comment by Allyans3** [comment]
> 36 CURLOPT_URL => self::mergeHeaders($this->getUrl()) what?))
> 
> microbans are still there.

Microbans can be caused due to the filter

**Comment by Giza** [comment]
> > 36 CURLOPT_URL => self::mergeHeaders($this->getUrl()) what?))
> > microbans are still there.
> 
> Microbans can be caused due to the filter [Микробаны могут быть вызваны фильтром]

i used only getItemOrdersHistogram
