### ISSUE TITLE
ItemListings method microbans

### ISSUE THREAD

**Issue by Dadungo** [Allyans3/steam-market-api-v2#7]
The maximum amount of requests per minute for the ItemListings method, as it is written in the wiki table, seems to be incorrect.

I tried cycling the exemple code with a delay of 40+ seconds between each call, and that always results in an Error 429 (too many requests) after 2/3 attempts maximum, even with only the 'market_hash_name' variable filled in the $options array and no other filter whatsoever.

**Comment by Allyans3** [comment]
You're right. 3 attempts and get code 429. I tested this a few weeks ago and it was 10+ attempts. Perhaps Steam has tightened the number of requests even more.

I'll try at night when Steam is less loaded and change the value in the table.

Thanks a lot.
