### ISSUE TITLE
I can't figure this out, Help <3

### ISSUE THREAD

**Issue by Bastion260** [Allyans3/steam-market-api-v2#9]
I'm far from beeing a programer and I'm a bit overwhelmed by this code . I downloaded and installed php as well as composer and followed your instructions, but still nothing. Can You add me on discord to give me some advices on hot to even run this thing? 
Discord : bajulka#8850

**Comment by Allyans3** [comment]
Answered

**Comment by Bastion260** [comment]
One more thing pls <3
